package com.enhyper.inputsanitiser.niql;

import org.ahocorasick.trie.Trie;
import org.ahocorasick.trie.Emit;
import java.util.Collection;

public class NiQLKeywordsTrie {
	
	private Trie trie = null;
	
	public NiQLKeywordsTrie() {

      this.trie = Trie.builder()
      .ignoreOverlaps() // Retain longest match
      .onlyWholeWords() 
      .caseInsensitive()
      .addKeyword("ALL")
      .addKeyword("ALTER")
      .addKeyword("ANALYZE")
      .addKeyword("AND")
      .addKeyword("ANY")
      .addKeyword("ARRAY")
      .addKeyword("AS")
      .addKeyword("ASC")
      .addKeyword("BEGIN")
      .addKeyword("BETWEEN")
      .addKeyword("BINARY")
      .addKeyword("BOOLEAN")
      .addKeyword("BREAK")
      .addKeyword("BUCKET")
      .addKeyword("BUILD")
      .addKeyword("BY")
      .addKeyword("CALL")
      .addKeyword("CASE")
      .addKeyword("CAST")
      .addKeyword("CLUSTER")
      .addKeyword("COLLATE")
      .addKeyword("COLLECTION")
      .addKeyword("COMMIT")
      .addKeyword("CONNECT")
      .addKeyword("CONTINUE")
      .addKeyword("CORRELATE")
      .addKeyword("COVER")
      .addKeyword("CREATE")
      .addKeyword("DATABASE")
      .addKeyword("DATASET")
      .addKeyword("DATASTORE")
      .addKeyword("DECLARE")
      .addKeyword("DECREMENT")
      .addKeyword("DELETE")
      .addKeyword("DERIVED")
      .addKeyword("DESC")
      .addKeyword("DESCRIBE")
      .addKeyword("DISTINCT")
      .addKeyword("DO")
      .addKeyword("DROP")
      .addKeyword("EACH")
      .addKeyword("ELEMENT")
      .addKeyword("ELSE")
      .addKeyword("END")
      .addKeyword("EVERY")
      .addKeyword("EXCEPT")
      .addKeyword("EXCLUDE")
      .addKeyword("EXECUTE")
      .addKeyword("EXISTS")
      .addKeyword("EXPLAIN")
      .addKeyword("FALSE")
      .addKeyword("FETCH")
      .addKeyword("FIRST")
      .addKeyword("FLATTEN")
      .addKeyword("FOR")
      .addKeyword("FORCE")
      .addKeyword("FROM")
      .addKeyword("FUNCTION")
      .addKeyword("GRANT")
      .addKeyword("GROUP")
      .addKeyword("GSI")
      .addKeyword("HAVING")
      .addKeyword("IF")
      .addKeyword("IGNORE")
      .addKeyword("ILIKE")
      .addKeyword("IN")
      .addKeyword("INCLUDE")
      .addKeyword("INCREMENT")
      .addKeyword("INDEX")
      .addKeyword("INFER")
      .addKeyword("INLINE")
      .addKeyword("INNER")
      .addKeyword("INSERT")
      .addKeyword("INTERSECT")
      .addKeyword("INTO")
      .addKeyword("IS")
      .addKeyword("JOIN")
      .addKeyword("KEY")
      .addKeyword("KEYS")
      .addKeyword("KEYSPACE")
      .addKeyword("KNOWN")
      .addKeyword("LAST")
      .addKeyword("LEFT")
      .addKeyword("LET")
      .addKeyword("LETTING")
      .addKeyword("LIKE")
      .addKeyword("LIMIT")
      .addKeyword("LSM")
      .addKeyword("MAP")
      .addKeyword("MAPPING")
      .addKeyword("MATCHED")
      .addKeyword("MATERIALIZED")
      .addKeyword("MERGE")
      .addKeyword("MINUS")
      .addKeyword("MISSING")
      .addKeyword("NAMESPACE")
      .addKeyword("NEST")
      .addKeyword("NOT")
      .addKeyword("NULL")
      .addKeyword("NUMBER")
      .addKeyword("OBJECT")
      .addKeyword("OFFSET")
      .addKeyword("ON")
      .addKeyword("OPTION")
      .addKeyword("OR")
      .addKeyword("ORDER")
      .addKeyword("OUTER")
      .addKeyword("OVER")
      .addKeyword("PARSE")
      .addKeyword("PARTITION")
      .addKeyword("PASSWORD")
      .addKeyword("PATH")
      .addKeyword("POOL")
      .addKeyword("PREPARE")
      .addKeyword("PRIMARY")
      .addKeyword("PRIVATE")
      .addKeyword("PRIVILEGE")
      .addKeyword("PROCEDURE")
      .addKeyword("PUBLIC")
      .addKeyword("RAW")
      .addKeyword("REALM")
      .addKeyword("REDUCE")
      .addKeyword("RENAME")
      .addKeyword("RETURN")
      .addKeyword("RETURNING")
      .addKeyword("REVOKE")
      .addKeyword("RIGHT")
      .addKeyword("ROLE")
      .addKeyword("ROLLBACK")
      .addKeyword("SATISFIES")
      .addKeyword("SCHEMA")
      .addKeyword("SELECT")
      .addKeyword("SELF")
      .addKeyword("SEMI")
      .addKeyword("SET")
      .addKeyword("SHOW")
      .addKeyword("SOME")
      .addKeyword("START")
      .addKeyword("STATISTICS")
      .addKeyword("STRING")
      .addKeyword("SYSTEM")
      .addKeyword("THEN")
      .addKeyword("TO")
      .addKeyword("TRANSACTION")
      .addKeyword("TRIGGER")
      .addKeyword("TRUE")
      .addKeyword("TRUNCATE")
      .addKeyword("UNDER")
      .addKeyword("UNION")
      .addKeyword("UNIQUE")
      .addKeyword("UNKNOWN")
      .addKeyword("UNNEST")
      .addKeyword("UNSET")
      .addKeyword("UPDATE")
      .addKeyword("UPSERT")
      .addKeyword("USE")
      .addKeyword("USER")
      .addKeyword("USING")
      .addKeyword("VALIDATE")
      .addKeyword("VALUE")
      .addKeyword("VALUED")
      .addKeyword("VALUES")
      .addKeyword("VIA")
      .addKeyword("VIEW")
      .addKeyword("WHEN")
      .addKeyword("WHERE")
      .addKeyword("WHILE")
      .addKeyword("WITH")
      .addKeyword("WITHIN")
      .addKeyword("WORK")
      .addKeyword("XOR")
      .build();
	}
	
	public int NiQLKeywordMatchCount(String user_input) {	
	   
		Collection<Emit> emits = this.trie.parseText(user_input);
	    return emits.size(); 
	}
	
	public Trie getNiQLTrie() {
		return this.trie;
	}
}
